use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

pub fn create_project(name: &str, template_id: &str) -> Result<()> {
    let template = crate::templates::find(template_id)
        .ok_or_else(|| anyhow::anyhow!("Unknown template: {template_id}"))?;

    let project_dir = Path::new(name);
    if project_dir.exists() {
        anyhow::bail!("Directory '{name}' already exists");
    }

    fs::create_dir(name)?;
    fs::create_dir(format!("{name}/src"))?;

    generate_common_files(name)?;
    let files = generate_source_files(name, template_id);
    for (path, content) in &files {
        fs::write(format!("{name}/{path}"), content)
            .with_context(|| format!("Failed to write {path}"))?;
    }

    let flake = make_flake(name, template.packages);
    fs::write(format!("{name}/flake.nix"), flake)?;

    Ok(())
}

fn generate_common_files(name: &str) -> Result<()> {
    fs::write(format!("{name}/.envrc"), "use flake\n")?;
    fs::write(
        format!("{name}/README.md"),
        format!("# {name}\n\nGenerated with forge\n"),
    )?;
    Ok(())
}

fn generate_source_files(name: &str, template_id: &str) -> Vec<(String, String)> {
    match template_id {
        "c" => gen_c_bare(name),
        "c-ncurses" => gen_c_ncurses(name),
        "c-raylib" => gen_c_raylib(name),
        "c-opengl" => gen_c_opengl(name),
        "c-sdl2" => gen_c_sdl2(name),
        "rust" => gen_rust(name),
        "python" => gen_python(name),
        _ => unreachable!(),
    }
}

fn make_flake(name: &str, packages: &[&str]) -> String {
    let pkgs: Vec<String> = packages
        .iter()
        .map(|p| format!("            {p}"))
        .collect();

    r#"# This file was generated by forge
{
  description = "{name}";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in
      {
        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [
{PACKAGES}
          ];
        };
      });
}
"#
    .replace("{name}", name)
    .replace("{PACKAGES}", &pkgs.join("\n"))
}

// -- C (bare) --

fn gen_c_bare(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.c".into(),
            r#"#include <stdio.h>

int main(void) {
    printf("Hello from {name}!\n");
    return 0;
}
"#
            .replace("{name}", name),
        ),
        (
            "Makefile".into(),
            r#"CC = gcc
CFLAGS = -Wall -Wextra -O2 -std=c11
LDFLAGS =
SRC = src/main.c
BIN = {name}

all: $(BIN)

$(BIN): $(SRC)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

run: $(BIN)
	./$(BIN)

clean:
	rm -f $(BIN)
.PHONY: all run clean
"#
            .replace("{name}", name),
        ),
    ]
}

// -- C with Ncurses --

fn gen_c_ncurses(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.c".into(),
            r#"#include <ncurses.h>

int main(void) {
    initscr();
    cbreak();
    noecho();
    clear();
    mvprintw(10, 10, "Hello from {name}!");
    refresh();
    getch();
    endwin();
    return 0;
}
"#
            .replace("{name}", name),
        ),
        (
            "Makefile".into(),
            r#"CC = gcc
CFLAGS = -Wall -Wextra -O2 -std=c11
LDFLAGS = -lncurses
SRC = src/main.c
BIN = {name}

all: $(BIN)

$(BIN): $(SRC)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

run: $(BIN)
	./$(BIN)

clean:
	rm -f $(BIN)
.PHONY: all run clean
"#
            .replace("{name}", name),
        ),
    ]
}

// -- C with Raylib --

fn gen_c_raylib(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.c".into(),
            r#"#include "raylib.h"

int main(void) {
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "{name}");
    SetTargetFPS(60);

    while (!WindowShouldClose()) {
        BeginDrawing();
        ClearBackground(RAYWHITE);
        DrawText("Hello from {name}!", 190, 200, 20, LIGHTGRAY);
        EndDrawing();
    }

    CloseWindow();
    return 0;
}
"#
            .replace("{name}", name),
        ),
        (
            "Makefile".into(),
            r#"CC = gcc
CFLAGS = -Wall -Wextra -O2 -std=c11 $(shell pkg-config --cflags raylib)
LDFLAGS = $(shell pkg-config --libs raylib)
SRC = src/main.c
BIN = {name}

all: $(BIN)

$(BIN): $(SRC)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

run: $(BIN)
	./$(BIN)

clean:
	rm -f $(BIN)
.PHONY: all run clean
"#
            .replace("{name}", name),
        ),
    ]
}

// -- C with OpenGL (GLFW) --

fn gen_c_opengl(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.c".into(),
            r#"#include <GLFW/glfw3.h>
#include <GL/gl.h>

int main(void) {
    if (!glfwInit())
        return -1;

    GLFWwindow* window = glfwCreateWindow(800, 600, "{name}", NULL, NULL);
    if (!window) {
        glfwTerminate();
        return -1;
    }

    glfwMakeContextCurrent(window);

    while (!glfwWindowShouldClose(window)) {
        glClear(GL_COLOR_BUFFER_BIT);

        glBegin(GL_TRIANGLES);
        glColor3f(1.0f, 0.0f, 0.0f); glVertex2f(-0.5f, -0.5f);
        glColor3f(0.0f, 1.0f, 0.0f); glVertex2f(0.5f, -0.5f);
        glColor3f(0.0f, 0.0f, 1.0f); glVertex2f(0.0f, 0.5f);
        glEnd();

        glfwSwapBuffers(window);
        glfwPollEvents();
    }

    glfwDestroyWindow(window);
    glfwTerminate();
    return 0;
}
"#
            .replace("{name}", name),
        ),
        (
            "Makefile".into(),
            r#"CC = gcc
CFLAGS = -Wall -Wextra -O2 -std=c11 $(shell pkg-config --cflags glfw3 gl)
LDFLAGS = $(shell pkg-config --libs glfw3 gl)
SRC = src/main.c
BIN = {name}

all: $(BIN)

$(BIN): $(SRC)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

run: $(BIN)
	./$(BIN)

clean:
	rm -f $(BIN)
.PHONY: all run clean
"#
            .replace("{name}", name),
        ),
    ]
}

// -- C with SDL2 --

fn gen_c_sdl2(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.c".into(),
            r#"#include <SDL2/SDL.h>

int main(void) {
    SDL_Init(SDL_INIT_VIDEO);

    SDL_Window* window = SDL_CreateWindow(
        "{name}",
        SDL_WINDOWPOS_UNDEFINED,
        SDL_WINDOWPOS_UNDEFINED,
        800, 600,
        SDL_WINDOW_SHOWN
    );

    SDL_Surface* surface = SDL_GetWindowSurface(window);
    SDL_FillRect(surface, NULL, SDL_MapRGB(surface->format, 0xFF, 0xFF, 0xFF));
    SDL_UpdateWindowSurface(window);
    SDL_Delay(3000);

    SDL_DestroyWindow(window);
    SDL_Quit();
    return 0;
}
"#
            .replace("{name}", name),
        ),
        (
            "Makefile".into(),
            r#"CC = gcc
CFLAGS = -Wall -Wextra -O2 -std=c11 $(shell pkg-config --cflags sdl2)
LDFLAGS = $(shell pkg-config --libs sdl2)
SRC = src/main.c
BIN = {name}

all: $(BIN)

$(BIN): $(SRC)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

run: $(BIN)
	./$(BIN)

clean:
	rm -f $(BIN)
.PHONY: all run clean
"#
            .replace("{name}", name),
        ),
    ]
}

// -- Rust --

fn gen_rust(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.rs".into(),
            r#"fn main() {
    println!("Hello from {name}!");
}
"#
            .replace("{name}", name),
        ),
        (
            "Cargo.toml".into(),
            r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"
"#
            .replace("{name}", name),
        ),
    ]
}

// -- Python --

fn gen_python(name: &str) -> Vec<(String, String)> {
    vec![(
        "src/main.py".into(),
        r#"def main():
    print("Hello from {name}!")


if __name__ == "__main__":
    main()
"#
        .replace("{name}", name),
    )]
}

// -- Add packages to existing flake.nix --

pub fn add_packages(name: &str, packages: &[String]) -> Result<()> {
    let flake_path = format!("{name}/flake.nix");
    let content =
        fs::read_to_string(&flake_path).with_context(|| format!("Failed to read {flake_path}"))?;

    let marker = "buildInputs = with pkgs; [";
    let marker_pos = content
        .find(marker)
        .ok_or_else(|| anyhow::anyhow!("Could not find buildInputs in flake.nix"))?;

    let after_marker = &content[marker_pos + marker.len()..];
    let close_pos = after_marker
        .find("];")
        .ok_or_else(|| anyhow::anyhow!("Could not find closing ] in buildInputs"))?;
    let close_abs = marker_pos + marker.len() + close_pos;

    // Walk back to the line start before the closing ];
    let insert_pos = content[..close_abs]
        .rfind('\n')
        .map(|p| p + 1)
        .unwrap_or(close_abs);

    let existing = &content[marker_pos + marker.len()..insert_pos];
    let to_add: Vec<&String> = packages
        .iter()
        .filter(|p| !existing.contains(p.as_str()))
        .collect();

    if to_add.is_empty() {
        println!("All packages already present");
        return Ok(());
    }

    let indent = "            ";
    let mut new_content = String::new();
    new_content.push_str(&content[..insert_pos]);
    for pkg in &to_add {
        new_content.push_str(&format!("{indent}{pkg}\n"));
    }
    new_content.push_str(&content[insert_pos..]);

    fs::write(&flake_path, new_content)?;
    let added: Vec<&str> = to_add.iter().map(|s| s.as_str()).collect();
    println!("Added packages: {}", added.join(", "));
    Ok(())
}
