use anyhow::Result;
use std::fs;


pub fn create_project(name: &str) -> Result<()> {

    fs::create_dir(name)?;

    fs::create_dir(
        format!("{}/src", name)
    )?;


    fs::write(
        format!("{}/.envrc", name),
        "use flake\n"
    )?;


    fs::write(
        format!("{}/flake.nix", name),
        "# generated by forge\n"
    )?;


    Ok(())
}
