use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

pub fn create_project(name: &str, template_id: &str) -> Result<()> {
    let template = crate::templates::find(template_id)
        .ok_or_else(|| anyhow::anyhow!("Unknown template: {template_id}"))?;

    let project_dir = Path::new(name);
    if project_dir.exists() {
        anyhow::bail!("Directory '{name}' already exists");
    }

    fs::create_dir(name)?;
    fs::create_dir(format!("{name}/src"))?;

    generate_common_files(name)?;
    let files = generate_source_files(name, template_id);
    for (path, content) in &files {
        let full_path = format!("{name}/{path}");
        if let Some(parent) = Path::new(&full_path).parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&full_path, content)
            .with_context(|| format!("Failed to write {path}"))?;
    }

    let flake = make_flake(name, template.packages);
    fs::write(format!("{name}/flake.nix"), flake)?;

    Ok(())
}

fn generate_common_files(name: &str) -> Result<()> {
    fs::write(format!("{name}/.envrc"), "use flake\n")?;
    fs::write(
        format!("{name}/README.md"),
        format!("# {name}\n\nGenerated with forge\n"),
    )?;
    Ok(())
}

fn generate_source_files(name: &str, template_id: &str) -> Vec<(String, String)> {
    match template_id {
        "c" => gen_c_bare(name),
        "c-allegro" => gen_c_allegro(name),
        "c-curl" => gen_c_curl(name),
        "c-gtk3" => gen_c_gtk3(name),
        "c-ncurses" => gen_c_ncurses(name),
        "c-opengl" => gen_c_opengl(name),
        "c-raylib" => gen_c_raylib(name),
        "c-sdl2" => gen_c_sdl2(name),
        "cpp" => gen_cpp(name),
        "go" => gen_go(name),
        "nodejs" => gen_nodejs(name),
        "python" => gen_python(name),
        "rust" => gen_rust(name),
        "zig" => gen_zig(name),
        _ => unreachable!(),
    }
}

// -- flake.nix generation --

fn make_flake(name: &str, packages: &[&str]) -> String {
    let pkgs: Vec<String> = packages
        .iter()
        .map(|p| format!("            {p}"))
        .collect();

    r#"# This file was generated by forge
{
  description = "{name}";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in
      {
        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [
{PACKAGES}
          ];
        };
      });
}
"#
    .replace("{name}", name)
    .replace("{PACKAGES}", &pkgs.join("\n"))
}

// -- Makefile helpers --

fn makefile_c(name: &str, extra_cflags: &str, extra_ldflags: &str) -> String {
    let cflags = if extra_cflags.is_empty() {
        String::from("CFLAGS = -Wall -Wextra -O2 -std=c11")
    } else {
        format!("CFLAGS = -Wall -Wextra -O2 -std=c11 {}", extra_cflags)
    };
    let ldflags = if extra_ldflags.is_empty() {
        String::from("LDFLAGS =")
    } else {
        format!("LDFLAGS = {}", extra_ldflags)
    };

    r#"BUILD_DIR = build
BIN = $(BUILD_DIR)/{name}

CC = gcc
{CFLAGS_TEMPLATE}
{LDFLAGS_TEMPLATE}
SRC = src/main.c

all: $(BIN)

$(BIN): $(SRC) | $(BUILD_DIR)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

$(BUILD_DIR):
	mkdir -p $@

run: $(BIN)
	./$(BIN)

clean:
	rm -rf $(BUILD_DIR)
.PHONY: all run clean
"#
    .replace("{name}", name)
    .replace("{CFLAGS_TEMPLATE}", &cflags)
    .replace("{LDFLAGS_TEMPLATE}", &ldflags)
}

fn makefile_cpp(name: &str, extra_cxxflags: &str, extra_ldflags: &str) -> String {
    let cxxflags = if extra_cxxflags.is_empty() {
        String::from("CXXFLAGS = -Wall -Wextra -O2 -std=c++17")
    } else {
        format!("CXXFLAGS = -Wall -Wextra -O2 -std=c++17 {}", extra_cxxflags)
    };
    let ldflags = if extra_ldflags.is_empty() {
        String::from("LDFLAGS =")
    } else {
        format!("LDFLAGS = {}", extra_ldflags)
    };

    r#"BUILD_DIR = build
BIN = $(BUILD_DIR)/{name}

CXX = g++
{CXXFLAGS_TEMPLATE}
{LDFLAGS_TEMPLATE}
SRC = src/main.cpp

all: $(BIN)

$(BIN): $(SRC) | $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

$(BUILD_DIR):
	mkdir -p $@

run: $(BIN)
	./$(BIN)

clean:
	rm -rf $(BUILD_DIR)
.PHONY: all run clean
"#
    .replace("{name}", name)
    .replace("{CXXFLAGS_TEMPLATE}", &cxxflags)
    .replace("{LDFLAGS_TEMPLATE}", &ldflags)
}

// -- C (bare) --

fn gen_c_bare(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.c".into(),
            r#"#include <stdio.h>

int main(void) {
    printf("Hello from {name}!\n");
    return 0;
}
"#
            .replace("{name}", name),
        ),
        ("Makefile".into(), makefile_c(name, "", "")),
    ]
}

// -- C with Allegro --

fn gen_c_allegro(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.c".into(),
            r#"#include <allegro5/allegro.h>

int main(void) {
    if (!al_init()) {
        al_uninstall_system();
        return -1;
    }

    ALLEGRO_DISPLAY *display = al_create_display(800, 600);
    if (!display) {
        al_uninstall_system();
        return -1;
    }

    al_set_window_title(display, "{name}");
    al_clear_to_color(al_map_rgb(24, 24, 24));
    al_flip_display();
    al_rest(3.0);

    al_destroy_display(display);
    al_uninstall_system();
    return 0;
}
"#
            .replace("{name}", name),
        ),
        (
            "Makefile".into(),
            makefile_c(
                name,
                "$(shell pkg-config --cflags allegro-5)",
                "$(shell pkg-config --libs allegro-5)",
            ),
        ),
    ]
}

// -- C with cURL --

fn gen_c_curl(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.c".into(),
            r#"#include <stdio.h>
#include <curl/curl.h>

static size_t write_cb(void *data, size_t size, size_t nmemb, void *user) {
    return fwrite(data, size, nmemb, stdout);
}

int main(void) {
    curl_global_init(CURL_GLOBAL_DEFAULT);

    CURL *curl = curl_easy_init();
    if (!curl) {
        fprintf(stderr, "Failed to init curl\n");
        curl_global_cleanup();
        return 1;
    }

    curl_easy_setopt(curl, CURLOPT_URL, "https://httpbin.org/get");
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_cb);

    CURLcode res = curl_easy_perform(curl);
    if (res != CURLE_OK)
        fprintf(stderr, "curl failed: %s\n", curl_easy_strerror(res));

    curl_easy_cleanup(curl);
    curl_global_cleanup();
    return 0;
}
"#
            .replace("{name}", name),
        ),
        (
            "Makefile".into(),
            makefile_c(
                name,
                "$(shell pkg-config --cflags libcurl)",
                "$(shell pkg-config --libs libcurl)",
            ),
        ),
    ]
}

// -- C with GTK3 --

fn gen_c_gtk3(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.c".into(),
            r#"#include <gtk/gtk.h>

static void on_activate(GtkApplication *app, gpointer data) {
    GtkWidget *win = gtk_application_window_new(app);
    gtk_window_set_title(GTK_WINDOW(win), "{name}");
    gtk_window_set_default_size(GTK_WINDOW(win), 400, 300);
    gtk_widget_show_all(win);
}

int main(int argc, char **argv) {
    GtkApplication *app = gtk_application_new("com.example.{name}",
                                              G_APPLICATION_DEFAULT_FLAGS);
    g_signal_connect(app, "activate", G_CALLBACK(on_activate), NULL);
    int status = g_application_run(G_APPLICATION(app), argc, argv);
    g_object_unref(app);
    return status;
}
"#
            .replace("{name}", name),
        ),
        (
            "Makefile".into(),
            makefile_c(
                name,
                "$(shell pkg-config --cflags gtk+-3.0)",
                "$(shell pkg-config --libs gtk+-3.0)",
            ),
        ),
    ]
}

// -- C with Ncurses --

fn gen_c_ncurses(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.c".into(),
            r#"#include <ncurses.h>

int main(void) {
    initscr();
    cbreak();
    noecho();
    clear();
    mvprintw(10, 10, "Hello from {name}!");
    refresh();
    getch();
    endwin();
    return 0;
}
"#
            .replace("{name}", name),
        ),
        ("Makefile".into(), makefile_c(name, "", "-lncurses")),
    ]
}

// -- C with OpenGL (GLFW) --

fn gen_c_opengl(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.c".into(),
            r#"#include <GLFW/glfw3.h>
#include <GL/gl.h>

int main(void) {
    if (!glfwInit())
        return -1;

    GLFWwindow *win = glfwCreateWindow(800, 600, "{name}", NULL, NULL);
    if (!win) {
        glfwTerminate();
        return -1;
    }

    glfwMakeContextCurrent(win);

    while (!glfwWindowShouldClose(win)) {
        glClear(GL_COLOR_BUFFER_BIT);

        glBegin(GL_TRIANGLES);
        glColor3f(1,0,0); glVertex2f(-0.5f, -0.5f);
        glColor3f(0,1,0); glVertex2f( 0.5f, -0.5f);
        glColor3f(0,0,1); glVertex2f( 0.0f,  0.5f);
        glEnd();

        glfwSwapBuffers(win);
        glfwPollEvents();
    }

    glfwDestroyWindow(win);
    glfwTerminate();
    return 0;
}
"#
            .replace("{name}", name),
        ),
        (
            "Makefile".into(),
            makefile_c(
                name,
                "$(shell pkg-config --cflags glfw3 gl)",
                "$(shell pkg-config --libs glfw3 gl)",
            ),
        ),
    ]
}

// -- C with Raylib --

fn gen_c_raylib(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.c".into(),
            r#"#include "raylib.h"

int main(void) {
    const int w = 800;
    const int h = 450;

    InitWindow(w, h, "{name}");
    SetTargetFPS(60);

    while (!WindowShouldClose()) {
        BeginDrawing();
        ClearBackground(RAYWHITE);
        DrawText("Hello from {name}!", 190, 200, 20, LIGHTGRAY);
        EndDrawing();
    }

    CloseWindow();
    return 0;
}
"#
            .replace("{name}", name),
        ),
        (
            "Makefile".into(),
            makefile_c(
                name,
                "$(shell pkg-config --cflags raylib)",
                "$(shell pkg-config --libs raylib)",
            ),
        ),
    ]
}

// -- C with SDL2 --

fn gen_c_sdl2(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.c".into(),
            r#"#include <SDL2/SDL.h>

int main(void) {
    SDL_Init(SDL_INIT_VIDEO);

    SDL_Window *win = SDL_CreateWindow(
        "{name}", SDL_WINDOWPOS_UNDEFINED,
        SDL_WINDOWPOS_UNDEFINED, 800, 600,
        SDL_WINDOW_SHOWN
    );

    SDL_Surface *surf = SDL_GetWindowSurface(win);
    SDL_FillRect(surf, NULL, SDL_MapRGB(surf->format, 0xFF, 0xFF, 0xFF));
    SDL_UpdateWindowSurface(win);
    SDL_Delay(3000);

    SDL_DestroyWindow(win);
    SDL_Quit();
    return 0;
}
"#
            .replace("{name}", name),
        ),
        (
            "Makefile".into(),
            makefile_c(
                name,
                "$(shell pkg-config --cflags sdl2)",
                "$(shell pkg-config --libs sdl2)",
            ),
        ),
    ]
}

// -- C++ (bare) --

fn gen_cpp(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.cpp".into(),
            r#"#include <iostream>

int main() {
    std::cout << "Hello from {name}!" << std::endl;
    return 0;
}
"#
            .replace("{name}", name),
        ),
        ("Makefile".into(), makefile_cpp(name, "", "")),
    ]
}

// -- Go --

fn gen_go(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.go".into(),
            r#"package main

import "fmt"

func main() {
    fmt.Println("Hello from {name}!")
}
"#
            .replace("{name}", name),
        ),
        (
            "go.mod".into(),
            r#"module {name}

go 1.22
"#
            .replace("{name}", name),
        ),
        (
            "Makefile".into(),
            r#"BUILD_DIR = build
BIN = $(BUILD_DIR)/{name}

all: $(BIN)

$(BIN): src/main.go go.mod | $(BUILD_DIR)
	go build -o $@ ./src

$(BUILD_DIR):
	mkdir -p $@

run: $(BIN)
	./$(BIN)

clean:
	rm -rf $(BUILD_DIR)
.PHONY: all run clean
"#
            .replace("{name}", name),
        ),
    ]
}

// -- Node.js --

fn gen_nodejs(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/index.js".into(),
            r#"const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
    res.statusCode = 200;
    res.setHeader('Content-Type', 'text/plain');
    res.end('Hello from {name}!\n');
});

server.listen(port, hostname, () => {
    console.log(`Server running at http://${hostname}:${port}/`);
});
"#
            .replace("{name}", name),
        ),
        (
            "package.json".into(),
            r#"{
  "name": "{name}",
  "version": "1.0.0",
  "private": true,
  "main": "src/index.js",
  "scripts": {
    "start": "node src/index.js"
  }
}
"#
            .replace("{name}", name),
        ),
    ]
}

// -- Python --

fn gen_python(name: &str) -> Vec<(String, String)> {
    vec![(
        "src/main.py".into(),
        r#"def main():
    print("Hello from {name}!")


if __name__ == "__main__":
    main()
"#
        .replace("{name}", name),
    )]
}

// -- Rust --

fn gen_rust(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.rs".into(),
            r#"fn main() {
    println!("Hello from {name}!");
}
"#
            .replace("{name}", name),
        ),
        (
            "Cargo.toml".into(),
            r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"
"#
            .replace("{name}", name),
        ),
    ]
}

// -- Zig --

fn gen_zig(name: &str) -> Vec<(String, String)> {
    vec![
        (
            "src/main.zig".into(),
            r#"const std = @import("std");

pub fn main() void {
    std.debug.print("Hello from {s}!\n", .{"{name}"});
}
"#
            .replace("{name}", name),
        ),
        (
            "Makefile".into(),
            r#"BUILD_DIR = build
BIN = $(BUILD_DIR)/{name}

all: $(BIN)

$(BIN): src/main.zig | $(BUILD_DIR)
	zig build-exe $< -femit-bin=$@

$(BUILD_DIR):
	mkdir -p $@

run: $(BIN)
	./$(BIN)

clean:
	rm -rf $(BUILD_DIR)
.PHONY: all run clean
"#
            .replace("{name}", name),
        ),
    ]
}

// -- Add packages to existing flake.nix --

pub fn add_packages(name: &str, packages: &[String]) -> Result<()> {
    let flake_path = format!("{name}/flake.nix");
    let content =
        fs::read_to_string(&flake_path).with_context(|| format!("Failed to read {flake_path}"))?;

    let marker = "buildInputs = with pkgs; [";
    let marker_pos = content
        .find(marker)
        .ok_or_else(|| anyhow::anyhow!("Could not find buildInputs in flake.nix"))?;

    let after_marker = &content[marker_pos + marker.len()..];
    let close_pos = after_marker
        .find("];")
        .ok_or_else(|| anyhow::anyhow!("Could not find closing ] in buildInputs"))?;
    let close_abs = marker_pos + marker.len() + close_pos;

    let insert_pos = content[..close_abs]
        .rfind('\n')
        .map(|p| p + 1)
        .unwrap_or(close_abs);

    let existing = &content[marker_pos + marker.len()..insert_pos];
    let to_add: Vec<&String> = packages
        .iter()
        .filter(|p| !existing.contains(p.as_str()))
        .collect();

    if to_add.is_empty() {
        println!("All packages already present");
        return Ok(());
    }

    let indent = "            ";
    let mut new_content = String::new();
    new_content.push_str(&content[..insert_pos]);
    for pkg in &to_add {
        new_content.push_str(&format!("{indent}{pkg}\n"));
    }
    new_content.push_str(&content[insert_pos..]);

    fs::write(&flake_path, new_content)?;
    let added: Vec<&str> = to_add.iter().map(|s| s.as_str()).collect();
    println!("Added packages: {}", added.join(", "));
    Ok(())
}
